### ISSUE TITLE
SOLUTION  SOLUTION 

### ISSUE THREAD

**Issue by enolife** [shamhi/TapSwapBot#104]
SOLUTION: add a Cache-Id: "random_8_alphanumeric_string_here" header to headers.py. Example: `"Cache-Id": "7EeXYO57"`

**Comment by enolife** [comment]
Find out how to make each request have a unique `Cache-Id` header

**Comment by alirezaalaeifaradonbeh** [comment]
Ok 👍 appreciation .

**Comment by mrdarkerr** [comment]
> Find out how to make each request have a unique `Cache-Id` header

def generate_random_string(length=8):
    characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    random_string = ''
    for _ in range(length):
        random_index = int((len(characters) * int.from_bytes(os.urandom(1), 'big')) / 256)
        random_string += characters[random_index]
    return random_string


generate_random_string()

**Comment by kingjan123** [comment]
it doesnt resolve this error
{"statusCode":400,"message":"invalid_chr[2]"}

**Comment by enolife** [comment]
> it doesnt resolve this error {"statusCode":400,"message":"invalid_chr[2]"}

Like i said, find out how to make each request  have a random Cache-Id value. your current code is reusing the same value for all requests once it is generated. find a way to change this

**Comment by kingjan123** [comment]
> > it doesnt resolve this error {"statusCode":400,"message":"invalid_chr[2]"}
> 
> Like i said, find out how to make each request have a random Cache-Id value. your current code is reusing the same value for all requests once it is generated. find a way to change this

as a i saw requests on broswer
each login step use differenet cache-id and after on all requests use the same till next login cycle
i implented this but still get error i think the time is important here as it takes 1-2 secodns to get chr with excuting script i think chr expires on this time

**Comment by enolife** [comment]
> > > it doesnt resolve this error {"statusCode":400,"message":"invalid_chr[2]"}
> > 
> > 
> > Like i said, find out how to make each request have a random Cache-Id value. your current code is reusing the same value for all requests once it is generated. find a way to change this
> 
> as a i saw requests on broswer each login step use differenet cache-id and after on all requests use the same till next login cycle i implented this but still get error i think the time is important here as it takes 1-2 secodns to get chr with excuting script i think chr expires on this time

I thought so too that chr expired too quickly, but that is not the case. You can keep login in with the same chr. It took me hours to narrow it down to that particular header. Use a tool like Burp repeater or other similar tools and find out.

**Comment by enolife** [comment]
don't forget to log your headers to see if changes takes place: print(response.request_info.headers)

**Comment by mrdarkerr** [comment]
> Find out how to make each request have a unique `Cache-Id` header

`def generate_random_string(length=8):
    return ''.join(choices(string.ascii_letters + string.digits, k=length))
    async def login(self, http_client: aiohttp.ClientSession, tg_web_data: str) -> tuple[dict[str], str]:
        response_text = ''
        try:
            response = await http_client.post(
                url='https://api.tapswap.ai/api/account/login',
                json={"init_data": tg_web_data, "referrer": ""},
                headers={"Cache-Id": generate_random_string()}
            )
            response_text = await response.text()
            # response.raise_for_status()

            response_json = await response.json()
            wait_s = response_json.get('wait_s')
            if wait_s:
                logger.error(f"{self.session_name} | App overloaded, waiting for: {wait_s}")
                await asyncio.sleep(delay=wait_s)
                return self.login(http_client, tg_web_data)

            chq = response_json.get('chq')

            if chq:
                async with self.lock:
                    chq_result = extract_chq(chq=chq)

                    response = await http_client.post(
                        url='https://api.tapswap.ai/api/account/login',
                        json={"chr": chq_result, "init_data": tg_web_data, "referrer": ""},
                        headers={"Cache-Id": generate_random_string()}
                    )
                    response_text = await response.text()
                    # response.raise_for_status()

                response_json = await response.json()
            access_token = response_json['access_token']
            profile_data = response_json

            return profile_data, access_token
        except Exception as error:
            traceback.print_exc()
            logger.error(f"{self.session_name} | Unknown error while getting Access Token: {error} | "
                         f"Response text: {escape_html(response_text)}...")
            await asyncio.sleep(delay=3)`

Does using a separate Cache-Id for each request mean something like this?
In this way, a new ID is created for each request that is sent

**Comment by MasudsCloud** [comment]
8 char long alphanumeric Cache-Id isn't the solution.
There is something odd happening. I already have tried this 12 hours ago, still the same issue. I think, it's the CORS/anti-spoof related problem, even though it says: Invalid chr (2).

**Comment by alirezaalaeifaradonbeh** [comment]
@headNbyte 
Hi Body

**Comment by MasudsCloud** [comment]
@headNbyte buddy come here 🍸

**Comment by MasudsCloud** [comment]
I'm gonna deal with it tomorrow 😒

**Comment by MasudsCloud** [comment]
Done :)

**Comment by ButCheR-PRO** [comment]
Same error,
1. https://github.com/shamhi/TapSwapBot/issues/112
