### ISSUE TITLE
Error Sir 

### ISSUE THREAD

**Issue by fiqi732** [shamhi/TapSwapBot#123]
![Screenshot (16)](https://github.com/shamhi/TapSwapBot/assets/168587624/0b04caaf-8dcf-444d-ad75-7291c31e33af)

**Comment by rez9r** [comment]
You banned account response invalid_request[3]
![Снимок экрана 2024-06-23 214049](https://github.com/shamhi/TapSwapBot/assets/89584308/fc4943cf-88cc-43fc-a12a-1203fee8477c)

**Comment by fiqi732** [comment]
@rez9r No sir

![IMG_7458](https://github.com/shamhi/TapSwapBot/assets/168587624/fc0f53c1-47d3-4cc4-9058-a1494434462d)

**Comment by rez9r** [comment]
Maybe it blocks api requests, it may work through the phone, didn't check, checked api and web if the response is invalid_request[3] then ban. It can be caught from any invalid request

**Comment by rez9r** [comment]
Maybe it blocks api requests, it may work through the phone, didn't check, checked api and web if the response is invalid_request[3] then ban. It can be caught from any invalid request
![photo_2024-06-24_14-09-21](https://github.com/shamhi/TapSwapBot/assets/89584308/a8369b11-6531-4d52-be46-22e797dcb1b5)

**Comment by rez9r** [comment]
To correct this error you need to fix user-agent and change headers 'X-Cv': '631', "X-touch": "0" 
But this is not enough, maybe something else is required because from a browser on a PC it blocks the account, but from a phone it does not.

**Comment by fiqi732** [comment]
@rez9r Then what should I do? Will my tapswap account be banned?

**Comment by rez9r** [comment]
Nothing so far unless you're a programmer and know a lot about it, I don't think any more updates will be posted. For the reason that now every bad request goes to the account ban, and for a successful reversal you can spend dozens of accounts. But I think it's all about headers

**Comment by fiqi732** [comment]
@rez9r Alright, thank you for your information sir

**Comment by Sagynbekov22** [comment]
Дайте инструкции на установку для MacOs
