### ISSUE TITLE
Add taps on turbo not working

### ISSUE THREAD

**Issue by icsan44** [shamhi/TapSwapBot#13]
i add like 10000000 for turbo use but the taps keep on the default one
dont know if its side server or client server

**Comment by 0zyyy** [comment]
Where do you add your turbo taps?

**Comment by shamhi** [comment]
> i add like 10000000 for turbo use but the taps keep on the default one dont know if its side server or client server

tapswap has limits


> Where do you add your turbo taps?

in .env
