### ISSUE TITLE
Требую помощь

### ISSUE THREAD

**Issue by SIXTVPE** [shamhi/TapSwapBot#2]
откорректировал конфиг-файл, пытался запустить на Убунту 20.04. сам дуб в этом.

![image](https://github.com/shamhi/TapSwapBot/assets/134633050/aea8432b-08ef-4b77-8be5-b7fa4e1663f8)

что не так?

**Comment by SireJeff** [comment]
У меня такая же проблема

**Comment by shrralis** [comment]
У меня было что-то похожее, после того как создал `.env` файл и заполнил его нормельно, всё запустилось
Кстати, была проблема что в `.env`-файле, скопированном с `.env-example`? надо было заменить `RANDOM_CLICKS_COUNT` на `RANDOM_TAPS_COUNT`

**Comment by shamhi** [comment]
проблема в версии питона, установите 3.10 или 3.11

**Comment by shamhi** [comment]
> У меня было что-то похожее, после того как создал `.env` файл и заполнил его нормельно, всё запустилось Кстати, была проблема ,что в `.env`-файле, скопированном с `.env-example`, надо было заменить `RANDOM_CLICKS_COUNT` на `RANDOM_TAPS_COUNT`

исправил, спасибо что заметил

**Comment by SIXTVPE** [comment]
> проблема в версии питона, установите 3.10 или 3.11

![image](https://github.com/shamhi/TapSwapBot/assets/134633050/8b13a6f9-851e-4a43-9d4e-0760e9181283)
теперь новая ошибка.

**Comment by shamhi** [comment]
у тебя че то не так с сетью, попробуй добавить этот код в `bot/core/tapper.py`
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by SIXTVPE** [comment]
> у тебя че то не так с сетью, попробуй добавить этот код в `bot/core/tapper.py`
> 
> ```python
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```

не спасло, вдс хуевый, наверное.
