### ISSUE TITLE
[WinError 193] %1 не является приложением Win32

### ISSUE THREAD

**Issue by SmILeTheMobster** [shamhi/TapSwapBot#217]
![image](https://github.com/user-attachments/assets/c1bc7dbd-51be-4b89-8dd2-ce1cf634855d)

**Comment by shelllshock** [comment]
Same/

**Comment by SmILeTheMobster** [comment]
[chromedriver-win64.zip](https://github.com/user-attachments/files/16770590/chromedriver-win64.zip)
I added this file inside TapSwapBot\webdriver and it worked

**Comment by SmILeTheMobster** [comment]
I added this file inside TapSwapBot\webdriver and it worked
[chromedriver-win64.zip](https://github.com/user-attachments/files/16770596/chromedriver-win64.zip)
