### ISSUE TITLE
Unknown error during Authorization: int too big to convert and SSL

### ISSUE THREAD

**Issue by benyusouf** [shamhi/TapSwapBot#24]
Can you help please? 

![image](https://github.com/shamhi/TapSwapBot/assets/26325624/8e60bd2a-557d-4b14-9676-788d9457c42f)

![image](https://github.com/shamhi/TapSwapBot/assets/26325624/5cefbf48-3719-41c0-906e-86e4398ccccb)

**Comment by shamhi** [comment]
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
