### ISSUE TITLE
error chromedriver

### ISSUE THREAD

**Issue by Vahid-Spacer** [shamhi/TapSwapBot#243]
2024-09-30 08:05:59 | ERROR    | 106 - spacer | Unknown error while Login: [Errno 8] Exec format error: 'webdriver/THIRD_PARTY_NOTICES.chromedriver' | Response text: ...

guys what should I do to fix this? ):

**Comment by mreeers** [comment]
Try installing chrome version 125 and delete the webdriver from the bot folder. It helped me

**Comment by upanasiuk** [comment]
Copy `chromedriver.exe` from `%userprofile%\.wdm\drivers\chromedriver\win64\<version>\chromedriver-win32` to webdriver\.
If error still appears, remove all other files from `webdriver`. Helped me for Win11 and Docker.
