### ISSUE TITLE
Ошибки при запуске скрипта

### ISSUE THREAD

**Issue by vedma1337** [shamhi/TapSwapBot#27]
![image](https://github.com/shamhi/TapSwapBot/assets/157295406/932ee78a-3d40-422c-af1a-aa51c5896474)
Получаю такие ошибки, не понимаю что за прикол с хешем, айди с хешем не перепутал, вроде бы должно все работать но выдает ошибки

**Comment by shamhi** [comment]
внимательно прочитай README
