### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by VasNick8064** [shamhi/TapSwapBot#29]
```
 ERROR  url=URL('https://api.tapswap.ai/api/account/login')
 | ERROR    | 315 - tapswap | Unknown error: cannot unpack non-iterable NoneType object
 | ERROR    | 86 - tapswap | Unknown error while getting Access Token: 408, message='Request Timeout', url=URL('https://api.tapswap.ai/api/account/login')
 | ERROR    | 315 - tapswap | Unknown error: cannot unpack non-iterable NoneType object
 | ERROR    | 86 - tapswap | Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.tapswap.ai/api/account/login')
 | ERROR    | 315 - tapswap | Unknown error: cannot unpack non-iterable NoneType object
 | ERROR    | 86 - tapswap | Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.tapswap.ai/api/account/login')
 | ERROR    | 315 - tapswap | Unknown error: cannot unpack non-iterable NoneType object
```

**Comment by Bakhtafarid** [comment]
![Screenshot 2024-05-23 113534](https://github.com/shamhi/TapSwapBot/assets/113907382/84be1639-0204-49c7-95b0-a48d0e055991)

**Comment by VasNick8064** [comment]
> ![Screenshot 2024-05-23 113534](https://private-user-images.githubusercontent.com/113907382/333094876-84be1639-0204-49c7-95b0-a48d0e055991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTIxNTYsIm5iZiI6MTcxNjQ1MTg1NiwicGF0aCI6Ii8xMTM5MDczODIvMzMzMDk0ODc2LTg0YmUxNjM5LTAyMDQtNDljNy05NWIwLWE0OGQwZTA1NTk5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzc2NjIwMjJjNDY1MWMyNDBmMDBjMGNlZWUwNGFkYzM5YWM4YmZiMDQ2OGVmYzVjYWQ0ZTFjYjRkYmIyZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TKw8ITljOP-JJ_a8ruYZkIfvvW3NJEgXmqmGNTfdP5A)

Ty m8
