### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by NkitN** [shamhi/TapSwapBot#30]
![image](https://github.com/shamhi/TapSwapBot/assets/95396947/a31e3694-f8fb-47a5-8f28-40a86d8cbd3c)

**Comment by shamhi** [comment]
use python version 3.11 or 3.10

**Comment by SannoV** [comment]
Такая же проблема , python 3.10.9 , весь порядок действий выполнялся по инструкции.
![image](https://github.com/shamhi/TapSwapBot/assets/45595167/59677713-7b01-410a-beed-d4ac25faea66)
![image](https://github.com/shamhi/TapSwapBot/assets/45595167/5a352901-1ddd-4731-be7d-8ed4bd36897d)
Пробовал и 3.11 , ситуация такая же.
![image](https://github.com/shamhi/TapSwapBot/assets/45595167/12a2fc61-3c32-4e02-b766-06e8c77e50e6)
