### ISSUE TITLE
Help pls 'Bad Request'

### ISSUE THREAD

**Issue by Antarctic12** [shamhi/TapSwapBot#33]
![image](https://github.com/shamhi/TapSwapBot/assets/170771978/2ff594bc-fdff-469f-bb90-ac8704a07c73)

I'm use proxies

Unknown error when Tapping: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/player/submit_taps') | Response text: {"statusCode":400,"message":"invalid_request[2]"}

**Comment by AlexKrutoy** [comment]
+
same without proxy

**Comment by mspet23** [comment]
+ same with proxy

**Comment by vtavn** [comment]
fixed

**Comment by matterisnanto** [comment]
> fixed

how?

**Comment by glofflive** [comment]
> fixed

??

**Comment by Antarctic12** [comment]
> fixed

where?

**Comment by Rollagit** [comment]
whats youre proxy providor ?
can u tell me an cheap and good proxy providor ?
i have webshare proxy but that proxys not working here

**Comment by Antarctic12** [comment]
> whats youre proxy providor ? can u tell me an cheap and good proxy providor ? i have webshare proxy but that proxys not working here

I use proxies a lot, these are resident proxies(https://t.me/buybee_bot,https://travchisproxies.com/)not advertising.

**Comment by fracturesky** [comment]
This is due to protection, not proxies, from ill-wishers. Some headers have been changed, and now you need to send a Content-Id when send_taps. They did the same with the login request, they changed the X-Cv

**Comment by Poryaei** [comment]
You can use my code from:  https://github.com/Poryaei/TapSwap-Clicker 😊

**Comment by fracturesky** [comment]
> You can use my code from: https://github.com/Poryaei/TapSwap-Clicker 😊

Bro, use python-dotenv to get variables, it's more reliable and secure

**Comment by Poryaei** [comment]
@fracturesky Thanks mate ❤️

**Comment by bond2bill** [comment]
> This is due to protection, not proxies, from ill-wishers. Some headers have been changed, and now you need to send a Content-Id when send_taps. They did the same with the login request, they changed the X-Cv #34

Bro, how to get Content-Id to make post request when send_tap()? i random and append header, but fail.

**Comment by shamhi** [comment]
fixed
