### ISSUE TITLE
Bad Request and How to Solve Them

### ISSUE THREAD

**Issue by enolife** [shamhi/TapSwapBot#35]
Lets begin...

**Comment by enolife** [comment]
async def login(self, http_client: aiohttp.ClientSession, tg_web_data: str) -> tuple[dict, str]:
            try:
                payload = {
                    "init_data": tg_web_data,
                    "referrer": "",
                    "bot_key": "app_bot_0"
                }
                response = await http_client.post(
                    url='https://api.tapswap.ai/api/account/login',
                    headers=headers,
                    json=payload  # correctly passing the Python dictionary
                )
                response.raise_for_status()
                response_json = await response.json()
                access_token = response_json["access_token"]
                http_client.headers["Authorization"] = f"Bearer {access_token}"
                profile_data = response_json
    
                return profile_data, access_token
            except Exception as error:
                logger.error(f"{self.session_name} | Unknown error while getting Access Token: {error}")
                await asyncio.sleep(3)
                raise

**Comment by shamhi** [comment]
fixed
