### ISSUE TITLE
error 408

### ISSUE THREAD

**Issue by Dxwny** [shamhi/TapSwapBot#39]
`2024-05-29 12:06:48 | ERROR    | 102 - rab | Unknown error while getting Access Token: 408, message='Request Timeout', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":408,"message":"request_error"}`

`in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('https://api.tapswap.ai/api/account/login')`

**Comment by general12345** [comment]
+

**Comment by MortezaVaezi2005** [comment]
i have it too

**Comment by Dxwny** [comment]
> i have it too

everything is fine now, apparently there is a problem on the part of the telegram
