### ISSUE TITLE
Failed to start clicker

### ISSUE THREAD

**Issue by Bx0lk** [shamhi/TapSwapBot#50]
Unknown error while getting Access Token: 'access_token' | Response text: {"chq":"b5fbe8f3fee9f4f2f3b5b4bde697e9efe4bde6f8ebfcf1b5bff9f2fee8f0f8f3e9b3faf8e9d8f1f8f0f8f3e9dfe4d4f9bfb4a6e0bdfefce9fef5bde6eff8e9e8eff3bdade5deaddbd8dfdcdfd8a6e097ebfcefbdf9bda0bdf9f2fee8f0f8f3e9a697ebfcefbdfabda0bdbffaf8e9d8f1f8f0f8f3e9dfe4d4f9bfa697ebfcefbdfcbda0bdbffaf8e9dce9e9eff4ffe8e9f8bfa697ebfcefbdefe9bda0bdf9c6fac0b5bfc2fef5efc2bfb4a697efe9c6bff4f3f3f8efbfbdb6bdbfd5c9d0bfbdb6bdbfd1bfc0bda0bdbaa1f9f4eba3a1f9f4ebbdf4f9a0bfc2fae9c2adbfbdc2f9c2a0bfaeaea9aaa8bfa3a1f9f4ebbdf4f9a0bfc2d2d3c2acbfbdc2f9c2a0bfabaeaba4aebfa3a1f9f4ebbdf4f9a0bfc2deccc2afbfbdc2f9c2a0bfa4a9aaa9a4bfa3a1f9f4ebbdf4f9a0bfc2dcccc2aebfbdc2f9c2a0bfa8aba8aeaabfa3a1f9f4ebbdf4f9a0bf"}

**Comment by Poryaei** [comment]
You can use my code:

https://github.com/Poryaei/TapSwap-Clicker/tree/main

:) Enjoy
