### ISSUE TITLE
Ошибки после некоторого времени работы

### ISSUE THREAD

**Issue by ATAMAH161** [shamhi/TapSwapBot#54]
![Безымянный](https://github.com/shamhi/TapSwapBot/assets/170763572/bce2270a-e5eb-4ee6-8601-944a825dfd88)

После некоторого времени безупречной работы выбивает на такие вот ошибки, скрипт обновлён до последней версии.

**Comment by monkiravn** [comment]
Tapswap's API was down. Retry after 2-3 hours later, guys

**Comment by ATAMAH161** [comment]
> Tapswap's API was down. Retry after 2-3 hours later, guys

Understood, thanks.

**Comment by Dxwny** [comment]
> > Tapswap's API was down. Retry after 2-3 hours later, guys
> 
> Understood, thanks.

close the issue if your problem has been solved
