### ISSUE TITLE
Ошибка при запуке

### ISSUE THREAD

**Issue by VasNick8064** [shamhi/TapSwapBot#58]
```
Traceback (most recent call last):
  File "/root/TapSwapBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/root/TapSwapBot/bot/core/tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
ModuleNotFoundError: No module named 'aiocfscrape'
```

**Comment by jm7uz** [comment]
> ```
> Traceback (most recent call last):
>   File "/root/TapSwapBot/main.py", line 4, in <module>
>     from bot.utils.launcher import process
>   File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
>     from . import launcher
>   File "/root/TapSwapBot/bot/utils/launcher.py", line 12, in <module>
>     from bot.core.tapper import run_tapper
>   File "/root/TapSwapBot/bot/core/tapper.py", line 7, in <module>
>     from aiocfscrape import CloudflareScraper
> ModuleNotFoundError: No module named 'aiocfscrape'
> ```

pip install aiocfscrape

**Comment by VasNick8064** [comment]
> > ```
> > Traceback (most recent call last):
> >   File "/root/TapSwapBot/main.py", line 4, in <module>
> >     from bot.utils.launcher import process
> >   File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
> >     from . import launcher
> >   File "/root/TapSwapBot/bot/utils/launcher.py", line 12, in <module>
> >     from bot.core.tapper import run_tapper
> >   File "/root/TapSwapBot/bot/core/tapper.py", line 7, in <module>
> >     from aiocfscrape import CloudflareScraper
> > ModuleNotFoundError: No module named 'aiocfscrape'
> > ```
> 
> 
> pip install aiocfscrape

не помогло

**Comment by VasNick8064** [comment]
Решено
