### ISSUE TITLE
Response 400 while hitting Tapswap API

### ISSUE THREAD

**Issue by hanafication** [shamhi/TapSwapBot#6]
Hi dude. Seems like got none response when hitting Tapswap API

 ``2024-04-25 10:56:55 | ERROR    | 86 - firswap | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')``
``2024-04-25 10:56:58 | ERROR    | 289 - firswap | Unknown error: cannot unpack non-iterable NoneType object``

Please, if these errors only mine, or others too? Thanks

**Comment by shamhi** [comment]
fixed
