### ISSUE TITLE
Error Js2py argument

### ISSUE THREAD

**Issue by IlhamEl777** [shamhi/TapSwapBot#73]
The error occurs specifically when running the script on an Ubuntu environment, while the same script runs without error on Windows. Here's the traceback of the error:

![image](https://github.com/shamhi/TapSwapBot/assets/106394125/f0d45f85-e6de-4803-8efb-38b8ddad524f)

**Comment by Savata-Rayma** [comment]
js2py is not supported in Python 3.12, I recommend installing Python 3.11.9.
