### ISSUE TITLE
ERROR SIR :(

### ISSUE THREAD

**Issue by fiqi732** [shamhi/TapSwapBot#82]
![Screenshot (6)](https://github.com/shamhi/TapSwapBot/assets/168587624/0f8a39ca-545a-4dd3-894b-58039b786207)

**Comment by Mikeyounger** [comment]
Same here

**Comment by kamranmt21** [comment]
Same problem

**Comment by rmnvskii** [comment]
Same too

**Comment by headNbyte** [comment]
@fiqi732 @Mikeyounger @kamranmt21 @rmnvskii Please try the latest commit.

**Comment by headNbyte** [comment]
@fiqi732 try to run the commands described inside install.sh, it looks like the repositories of firefox were not registered in your system

**Comment by fiqi732** [comment]
@headNbyte when I want to install Firefox I find a warning like this
![Screenshot (8)](https://github.com/shamhi/TapSwapBot/assets/168587624/eb2b9032-f16d-4797-b04f-37c8f48a12eb)

**Comment by headNbyte** [comment]
@fiqi732 
```

sudo apt update
sudo apt install -y software-properties-common

sudo add-apt-repository -y ppa:mozillateam/ppa
sudo tee /etc/apt/preferences.d/mozilla-firefox <<EOF
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
EOF

sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox <<EOF
Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:\${distro_codename}";
EOF

sudo apt update
sudo apt upgrade
sudo apt install -y firefox

sudo tee -a /etc/hosts <<EOF
127.0.0.1 localhost
EOF
```

**Comment by fiqi732** [comment]
@headNbyte 
┌──(fiqi㉿DESKTOP-D5SQ39M)-[~]
└─$ sudo add-apt-repository -y ppa:mozillateam/ppa
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

┌──(fiqi㉿DESKTOP-D5SQ39M)-[~]
└─$

**Comment by headNbyte** [comment]
@fiqi732 this is a Termux issue that you need to solve, try to search on the web how to install the firefox on Termux.

**Comment by kamranmt21** [comment]
@fiqi732 @Mikeyounger @rmnvskii 
with the last update, now it has started working for me on Termux.
