### ISSUE TITLE
Error in termux

### ISSUE THREAD

**Issue by Rickyrvxlovet** [shamhi/TapSwapBot#90]
![IMG_20240616_203629](https://github.com/shamhi/TapSwapBot/assets/138698343/caa2df8d-1d1f-4321-8078-7b2a00211488)

@headNbyte  How can I fix this error?

**Comment by headNbyte** [comment]
@Rickyrvxlovet Unfortunately, I don't know. From the output looks like an issue with firefox itself.
You may try following commands:
```
sudo apt purge firefox
sudo apt update
sudo apt upgrade
sudo sh install.sh
```

**Comment by celepok** [comment]
I have the same issue
